### ISSUE TITLE
MovableListView not responding on some iPhones : Solved?

### ISSUE THREAD

**Issue by TechyMiss** [isychev93/Xamarin.Forms-Drag-and-drop-ListView#1]
Hello,
I've recently integrated this MovableListView into my Xamarin Forms project.
iPhone 5 with the model type of NE496LL/A do not have an issue with the MLV and respond properly.
However, newer models of iPhone do not seem to be responding.
My guess is that there is an issue with how the UILongTouchGesture is interpreted.

Is this a common issue? If so, has there been a remedy that others are using?
If I find the answer myself I will reply to this thread with the code.

Thank you again for this otherwise wonderful solution!

**Comment by TechyMiss** [comment]
I think I found the answer,

Importing the files directly rather than using the compiled .dll files seems to have fixed the issues I was having.

**Comment by isychev93** [comment]
Hello. Are you slove problem?

**Comment by isychev93** [comment]
Maybe you forgot about  `[assembly: ExportRenderer(typeof(MovableViewCell), typeof(MovableViewCellRenderer))]` ?
